# Generated by Django 5.2 on 2025-04-27 19:10

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField(unique=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('last_fetched', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sources',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('url', models.TextField(unique=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('fake_score', models.FloatField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.ManyToManyField(related_name='articles', to='news.keyword')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.sources')),
            ],
            options={
                'db_table': 'articles',
                'managed': True,
                'indexes': [models.Index(fields=['published_date'], name='articles_publish_ab562d_idx'), models.Index(fields=['source'], name='articles_source__bca100_idx'), models.Index(fields=['category'], name='articles_categor_052161_idx')],
            },
        ),
    ]
