# Generated by Django 5.1.6 on 2025-02-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='keywords',
            field=models.ManyToManyField(related_name='articles', to='news.keyword'),
        ),
    ]
