# Generated by Django 5.2 on 2025-05-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_recommendation_userinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='location',
            new_name='country',
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
