# Generated by Django 5.2 on 2025-05-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_embedding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articles',
            name='articles_categor_052161_idx',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
    ]
