# Generated by Django 5.2 on 2025-05-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_category_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_fake',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['is_fake'], name='articles_is_fake_048493_idx'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['sentiment'], name='articles_sentime_a50a80_idx'),
        ),
    ]
