# Generated by Django 5.2 on 2025-05-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.feed'),
        ),
        migrations.AddField(
            model_name='articles',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
