# Generated by Django 5.2 on 2025-05-26 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_savedcollection_savedarticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='strength',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'interaction_type'], name='news_userin_user_id_e0b5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['article'], name='news_userin_article_4fcf21_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['timestamp'], name='news_userin_timesta_4ee131_idx'),
        ),
    ]
